services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # expõe apenas o frontend
    networks:
      - appnet
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000" # only expose to frontend container and not for anyone else
    networks:
      - appnet

networks:
  appnet:
    driver: bridge